version: "3.1"

# :redir @* | !openssl rand -base64 32 | tr -d '\n' | xclip -selection clipboard
# Replace secret_key:
# 12,$s/SECRET_KEY=""/SECRET_KEY=""
# 12,$s/SECRET_KEY="*.*"/SECRET_KEY=""
#
# Replace all the database credentials
# 10s/entity/<...>/g
# 12,$s/base:base@database\/base/entity:entity@database\/entity/g

networks:
  default:

services:
  database:
    image: postgres:13-alpine
    networks: ["default"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: base
      POSTGRES_PASSWORD: base
    command: [ "docker-entrypoint.sh", "-c", "wal_level=logical", "-c", "max_connections=300" ]

# {{{
  # web:
  #   image: kennycallado/q-app-web:latest
  #   ports:
  #     - 8000:80

  # admin:
  #   image: kennycallado/q-app-admin:latest
  #   ports:
  #     - 8080:80
# }}}

# {{{ messages
  messages_api:
    image: kennycallado/q-api-messages:latest
    networks: ["default"]
    ports:
      - "8005:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
# }}}

# {{{ profiles - users - auth
  # {{{ profiles
  profiles_api:
    image: kennycallado/q-api-profiles:latest
    networks: ["default"]
    ports:
      - "8001:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
  # }}}

  # {{{ users
  users_api:
    image: kennycallado/q-api-users:latest
    networks: ["default"]
    ports:
      - "8002:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
  # }}}

  # {{{ auth
  auth_api:
    image: kennycallado/q-api-auth:latest
    networks: ["default"]
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ports:
      - "8003:8000"

    environment:
      - ROCKET_ORIGIN_URL="http://localhost:8000,http://localhost:8080"
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
    depends_on:
      - users_api
  # }}}
# }}}

# {{{ questions - answers
  # {{{ questions
  questions_api:
    image: kennycallado/q-api-questions:0.1.5
    networks: ["default"]
    ports:
      - "8011:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - users_api
  # }}}

  # {{{ answers
  answers_api:
    image: kennycallado/q-api-answers:latest
    networks: ["default"]
    ports:
      - "8012:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - questions_api
  # }}}
# }}}

# {{{ slides
  # {{{ slides
  slides_api:
    image: kennycallado/q-api-slides:latest
    networks: ["default"]
    ports:
      - "8021:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - questions_api
  # }}}
# }}}

# {{{ resources - papers
  # {{{ resources
  resources_api:
    image: kennycallado/q-api-resources:latest
    networks: ["default"]
    ports:
      - "8031:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - slides_api
  # }}}

  # {{{ papers
  papers_api:
    image: kennycallado/q-api-papers:latest
    networks: ["default"]
    ports:
      - "8032:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - resources_api
  # }}}
# }}}

# {{{ checker - logics
  # {{{ checker
  checker_api:
    image: kennycallado/q-api-checker:latest
    networks: ["default"]
    ports:
      - "3000:3000"

    volumes:
      - scripts:/app/SCRIPTS
  # }}}

  # {{{ logics and logics-cron
  logics_api:
    image: kennycallado/q-api-logics:latest
    networks: ["default"]
    ports:
      - "8041:8000"

    volumes:
      - scripts:/root/SCRIPTS
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - checker_api
      - projects_api
      - users_api

  logics-cron_api:
    image: kennycallado/q-api-logics:latest
    networks: ["default"]
    volumes:
      - scripts:/root/SCRIPTS
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - checker_api
      - projects_api
      - users_api
  # }}}
# }}}

# {{{ projects - cron
  # {{{ projects
  projects_api:
    image: kennycallado/q-api-projects:latest
    networks: ["default"]
    ports:
      - "8051:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
  # }}}

  # {{{ cron
  cron_api:
    image: kennycallado/q-api-cron:latest
    networks: ["default"]
    ports:
      - "8052:8000"

    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://base:base@database/base"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics-cron_api:8000/api/v1/logic/"
      # - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - logics_api
  # }}}
# }}}

volumes:
  scripts:
